
let spriteGraphics = {
  winner: require("../assets/winner.png"),
  virus :     require("../assets/sprites/virus_dark.png"),
  brown_virus :     require("../assets/sprites/brown_virus.png"),
  purple_virus:   require("../assets/sprites/purple_virus.png"),
  cyan_virus:   require("../assets/sprites/cyan_virus.png"),
  
  life: require("../assets/sprites/life.png"),
  syringe_left: require("../assets/sprites/syringe_left.png"),
  syringe_right: require("../assets/sprites/syringe_right.png"),
  syringe_up: require("../assets/sprites/syringe_up.png"),
  syringe_down: require("../assets/sprites/syringe_down.png"),

  syringe_red_left: require("../assets/sprites/syringe_red_left.png"),
  syringe_red_right: require("../assets/sprites/syringe_red_right.png"),
  syringe_red_up: require("../assets/sprites/syringe_red_up.png"),
  syringe_red_down: require("../assets/sprites/syringe_red_down.png"),

  syringe_blue_left: require("../assets/sprites/syringe_blue_left.png"),
  syringe_blue_right: require("../assets/sprites/syringe_blue_right.png"),
  syringe_blue_up: require("../assets/sprites/syringe_blue_up.png"),
  syringe_blue_down: require("../assets/sprites/syringe_blue_down.png"),

  explosion_0 : require("../assets/sprites/explosion_0.png"),
  explosion_1 : require("../assets/sprites/explosion_1.png"),
  explosion_2 : require("../assets/sprites/explosion_2.png"),
  explosion_3 : require("../assets/sprites/explosion_3.png"),
  explosion_4 : require("../assets/sprites/explosion_4.png"),
  explosion_5 : require("../assets/sprites/explosion_5.png"),
  explosion_6 : require("../assets/sprites/explosion_6.png"),

  grey_bowl : require("../assets/sprites/grey_bowl.png"),
  red_bowl : require("../assets/sprites/red_bowl.png"),
  green_bowl : require("../assets/sprites/green_bowl.png"),

  black_testtube : require("../assets/sprites/black_testtube.png"),
  brown_testtube : require("../assets/sprites/brown_testtube.png"),
  cyan_testtube :  require("../assets/sprites/cyan_testtube.png"),
  purple_testtube :  require("../assets/sprites/purple_testtube.png"),

  red_key: require("../assets/sprites/red_key.png"),
  green_key: require("../assets/sprites/green_key.png"),
  yellow_key: require("../assets/sprites/yellow_key.png"),
  blue_key: require("../assets/sprites/blue_key.png"),
  crown: require("../assets/sprites/crown.png"),

  red_door_1: require("../assets/sprites/red_door_1.png"),
  red_door_2: require("../assets/sprites/red_door_2.png"),  
  red_door_3: require("../assets/sprites/red_door_3.png"),
  red_door_4: require("../assets/sprites/red_door_4.png"),

  green_door_1: require("../assets/sprites/green_door_1.png"),
  green_door_2: require("../assets/sprites/green_door_2.png"),  
  green_door_3: require("../assets/sprites/green_door_3.png"),
  green_door_4: require("../assets/sprites/green_door_4.png"),
  
  yellow_door_1: require("../assets/sprites/yellow_door_1.png"),
  yellow_door_2: require("../assets/sprites/yellow_door_2.png"),  
  yellow_door_3: require("../assets/sprites/yellow_door_3.png"),
  yellow_door_4: require("../assets/sprites/yellow_door_4.png"),
  
  blue_door_1: require("../assets/sprites/blue_door_1.png"),
  blue_door_2: require("../assets/sprites/blue_door_2.png"),  
  blue_door_3: require("../assets/sprites/blue_door_3.png"),
  blue_door_4: require("../assets/sprites/blue_door_4.png"),
  
  globeTrotter_left_0 : require("../assets/sprites/globaltrotter_left_0.png"),
  globeTrotter_left_1 : require("../assets/sprites/globaltrotter_left_1.png"),
  globeTrotter_left_2 : require("../assets/sprites/globaltrotter_left_2.png"),
  globeTrotter_left_3 : require("../assets/sprites/globaltrotter_left_3.png"),
  globeTrotter_left_4 : require("../assets/sprites/globaltrotter_left_4.png"),
  globeTrotter_left_5 : require("../assets/sprites/globaltrotter_left_5.png"),
  globeTrotter_left_6 : require("../assets/sprites/globaltrotter_left_6.png"),
  globeTrotter_left_7 : require("../assets/sprites/globaltrotter_left_7.png"),
  globeTrotter_left_8 : require("../assets/sprites/globaltrotter_left_8.png"),
  globeTrotter_left_9 : require("../assets/sprites/globaltrotter_left_9.png"),
  globeTrotter_left_10 : require("../assets/sprites/globaltrotter_left_10.png"),
  globeTrotter_left_11 : require("../assets/sprites/globaltrotter_left_11.png"),
  globeTrotter_left_12 : require("../assets/sprites/globaltrotter_left_12.png"),
  globeTrotter_left_13 : require("../assets/sprites/globaltrotter_left_13.png"),
  globeTrotter_left_14 : require("../assets/sprites/globaltrotter_left_14.png"),
  globeTrotter_left_15 : require("../assets/sprites/globaltrotter_left_15.png"),

  globeTrotter_right_0 : require("../assets/sprites/globaltrotter_right_0.png"),
  globeTrotter_right_1 : require("../assets/sprites/globaltrotter_right_1.png"),
  globeTrotter_right_2 : require("../assets/sprites/globaltrotter_right_2.png"),
  globeTrotter_right_3 : require("../assets/sprites/globaltrotter_right_3.png"),
  globeTrotter_right_4 : require("../assets/sprites/globaltrotter_right_4.png"),
  globeTrotter_right_5 : require("../assets/sprites/globaltrotter_right_5.png"),
  globeTrotter_right_6 : require("../assets/sprites/globaltrotter_right_6.png"),
  globeTrotter_right_7 : require("../assets/sprites/globaltrotter_right_7.png"),
  globeTrotter_right_8 : require("../assets/sprites/globaltrotter_right_8.png"),
  globeTrotter_right_9 : require("../assets/sprites/globaltrotter_right_9.png"),
  globeTrotter_right_10 : require("../assets/sprites/globaltrotter_right_10.png"),
  globeTrotter_right_11 : require("../assets/sprites/globaltrotter_right_11.png"),
  globeTrotter_right_12 : require("../assets/sprites/globaltrotter_right_12.png"),
  globeTrotter_right_13 : require("../assets/sprites/globaltrotter_right_13.png"),
  globeTrotter_right_14 : require("../assets/sprites/globaltrotter_right_14.png"),
  globeTrotter_right_15 : require("../assets/sprites/globaltrotter_right_15.png"),  

  globeTrotter_up_0 : require("../assets/sprites/globaltrotter_up_0.png"),
  globeTrotter_up_1 : require("../assets/sprites/globaltrotter_up_1.png"),
  globeTrotter_up_2 : require("../assets/sprites/globaltrotter_up_2.png"),
  globeTrotter_up_3 : require("../assets/sprites/globaltrotter_up_3.png"),
  globeTrotter_up_4 : require("../assets/sprites/globaltrotter_up_4.png"),
  globeTrotter_up_5 : require("../assets/sprites/globaltrotter_up_5.png"),
  globeTrotter_up_6 : require("../assets/sprites/globaltrotter_up_6.png"),
  globeTrotter_up_7 : require("../assets/sprites/globaltrotter_up_7.png"),
  globeTrotter_up_8 : require("../assets/sprites/globaltrotter_up_8.png"),
  globeTrotter_up_9 : require("../assets/sprites/globaltrotter_up_9.png"),
  globeTrotter_up_10 : require("../assets/sprites/globaltrotter_up_10.png"),
  globeTrotter_up_11 : require("../assets/sprites/globaltrotter_up_11.png"),
  globeTrotter_up_12 : require("../assets/sprites/globaltrotter_up_12.png"),
  globeTrotter_up_13 : require("../assets/sprites/globaltrotter_up_13.png"),
  globeTrotter_up_14 : require("../assets/sprites/globaltrotter_up_14.png"),
  globeTrotter_up_15 : require("../assets/sprites/globaltrotter_up_15.png"),
  
  globeTrotter_down_0 : require("../assets/sprites/globaltrotter_down_0.png"),
  globeTrotter_down_1 : require("../assets/sprites/globaltrotter_down_1.png"),
  globeTrotter_down_2 : require("../assets/sprites/globaltrotter_down_2.png"),
  globeTrotter_down_3 : require("../assets/sprites/globaltrotter_down_3.png"),
  globeTrotter_down_4 : require("../assets/sprites/globaltrotter_down_4.png"),
  globeTrotter_down_5 : require("../assets/sprites/globaltrotter_down_5.png"),
  globeTrotter_down_6 : require("../assets/sprites/globaltrotter_down_6.png"),
  globeTrotter_down_7 : require("../assets/sprites/globaltrotter_down_7.png"),
  globeTrotter_down_8 : require("../assets/sprites/globaltrotter_down_8.png"),
  globeTrotter_down_9 : require("../assets/sprites/globaltrotter_down_9.png"),
  globeTrotter_down_10 : require("../assets/sprites/globaltrotter_down_10.png"),
  globeTrotter_down_11 : require("../assets/sprites/globaltrotter_down_11.png"),
  globeTrotter_down_12 : require("../assets/sprites/globaltrotter_down_12.png"),
  globeTrotter_down_13 : require("../assets/sprites/globaltrotter_down_13.png"),
  globeTrotter_down_14 : require("../assets/sprites/globaltrotter_down_14.png"),
  globeTrotter_down_15 : require("../assets/sprites/globaltrotter_down_15.png"),
  
  grey_bat_left_0: require("../assets/sprites/grey_bat_left_0.png"),
  grey_bat_left_1: require("../assets/sprites/grey_bat_left_1.png"),
  grey_bat_left_2: require("../assets/sprites/grey_bat_left_2.png"),
  grey_bat_left_3: require("../assets/sprites/grey_bat_left_3.png"),
  grey_bat_left_4: require("../assets/sprites/grey_bat_left_4.png"),  
  grey_bat_left_5: require("../assets/sprites/grey_bat_left_5.png"),
  grey_bat_left_6: require("../assets/sprites/grey_bat_left_6.png"),
  grey_bat_left_7: require("../assets/sprites/grey_bat_left_7.png"),
  grey_bat_left_8: require("../assets/sprites/grey_bat_left_8.png"),
  grey_bat_left_9: require("../assets/sprites/grey_bat_left_9.png"),
  grey_bat_left_10: require("../assets/sprites/grey_bat_left_10.png"),
  grey_bat_left_11: require("../assets/sprites/grey_bat_left_11.png"),
  grey_bat_left_12: require("../assets/sprites/grey_bat_left_12.png"),
  grey_bat_left_13: require("../assets/sprites/grey_bat_left_13.png"),
  grey_bat_left_14: require("../assets/sprites/grey_bat_left_14.png"),  
  grey_bat_left_15: require("../assets/sprites/grey_bat_left_15.png"),
  grey_bat_left_16: require("../assets/sprites/grey_bat_left_16.png"),
  grey_bat_left_17: require("../assets/sprites/grey_bat_left_17.png"),
  grey_bat_left_18: require("../assets/sprites/grey_bat_left_18.png"),
  grey_bat_left_19: require("../assets/sprites/grey_bat_left_19.png"),   

  grey_bat_right_0: require("../assets/sprites/grey_bat_right_0.png"),
  grey_bat_right_1: require("../assets/sprites/grey_bat_right_1.png"),
  grey_bat_right_2: require("../assets/sprites/grey_bat_right_2.png"),
  grey_bat_right_3: require("../assets/sprites/grey_bat_right_3.png"),
  grey_bat_right_4: require("../assets/sprites/grey_bat_right_4.png"),  
  grey_bat_right_5: require("../assets/sprites/grey_bat_right_5.png"),
  grey_bat_right_6: require("../assets/sprites/grey_bat_right_6.png"),
  grey_bat_right_7: require("../assets/sprites/grey_bat_right_7.png"),
  grey_bat_right_8: require("../assets/sprites/grey_bat_right_8.png"),
  grey_bat_right_9: require("../assets/sprites/grey_bat_right_9.png"),
  grey_bat_right_10: require("../assets/sprites/grey_bat_right_10.png"),
  grey_bat_right_11: require("../assets/sprites/grey_bat_right_11.png"),
  grey_bat_right_12: require("../assets/sprites/grey_bat_right_12.png"),
  grey_bat_right_13: require("../assets/sprites/grey_bat_right_13.png"),
  grey_bat_right_14: require("../assets/sprites/grey_bat_right_14.png"),  
  grey_bat_right_15: require("../assets/sprites/grey_bat_right_15.png"),
  grey_bat_right_16: require("../assets/sprites/grey_bat_right_16.png"),
  grey_bat_right_17: require("../assets/sprites/grey_bat_right_17.png"),
  grey_bat_right_18: require("../assets/sprites/grey_bat_right_18.png"),
  grey_bat_right_19: require("../assets/sprites/grey_bat_right_19.png"),     

  grey_bat_up_0: require("../assets/sprites/grey_bat_up_0.png"),
  grey_bat_up_1: require("../assets/sprites/grey_bat_up_1.png"),
  grey_bat_up_2: require("../assets/sprites/grey_bat_up_2.png"),
  grey_bat_up_3: require("../assets/sprites/grey_bat_up_3.png"),
  grey_bat_up_4: require("../assets/sprites/grey_bat_up_4.png"),  
  grey_bat_up_5: require("../assets/sprites/grey_bat_up_5.png"),
  grey_bat_up_6: require("../assets/sprites/grey_bat_up_6.png"),
  grey_bat_up_7: require("../assets/sprites/grey_bat_up_7.png"),
  grey_bat_up_8: require("../assets/sprites/grey_bat_up_8.png"),
  grey_bat_up_9: require("../assets/sprites/grey_bat_up_9.png"),
  grey_bat_up_10: require("../assets/sprites/grey_bat_up_10.png"),
  grey_bat_up_11: require("../assets/sprites/grey_bat_up_11.png"),
  grey_bat_up_12: require("../assets/sprites/grey_bat_up_12.png"),
  grey_bat_up_13: require("../assets/sprites/grey_bat_up_13.png"),
  grey_bat_up_14: require("../assets/sprites/grey_bat_up_14.png"),  
  grey_bat_up_15: require("../assets/sprites/grey_bat_up_15.png"),
  grey_bat_up_16: require("../assets/sprites/grey_bat_up_16.png"),
  grey_bat_up_17: require("../assets/sprites/grey_bat_up_17.png"),
  grey_bat_up_18: require("../assets/sprites/grey_bat_up_18.png"),
  grey_bat_up_19: require("../assets/sprites/grey_bat_up_19.png"),

  grey_bat_down_0: require("../assets/sprites/grey_bat_down_0.png"),
  grey_bat_down_1: require("../assets/sprites/grey_bat_down_1.png"),
  grey_bat_down_2: require("../assets/sprites/grey_bat_down_2.png"),
  grey_bat_down_3: require("../assets/sprites/grey_bat_down_3.png"),
  grey_bat_down_4: require("../assets/sprites/grey_bat_down_4.png"),  
  grey_bat_down_5: require("../assets/sprites/grey_bat_down_5.png"),
  grey_bat_down_6: require("../assets/sprites/grey_bat_down_6.png"),
  grey_bat_down_7: require("../assets/sprites/grey_bat_down_7.png"),
  grey_bat_down_8: require("../assets/sprites/grey_bat_down_8.png"),
  grey_bat_down_9: require("../assets/sprites/grey_bat_down_9.png"),
  grey_bat_down_10: require("../assets/sprites/grey_bat_down_10.png"),
  grey_bat_down_11: require("../assets/sprites/grey_bat_down_11.png"),
  grey_bat_down_12: require("../assets/sprites/grey_bat_down_12.png"),
  grey_bat_down_13: require("../assets/sprites/grey_bat_down_13.png"),
  grey_bat_down_14: require("../assets/sprites/grey_bat_down_14.png"),  
  grey_bat_down_15: require("../assets/sprites/grey_bat_down_15.png"),
  grey_bat_down_16: require("../assets/sprites/grey_bat_down_16.png"),
  grey_bat_down_17: require("../assets/sprites/grey_bat_down_17.png"),
  grey_bat_down_18: require("../assets/sprites/grey_bat_down_18.png"),
  grey_bat_down_19: require("../assets/sprites/grey_bat_down_19.png"), 
  
  grey_bat_nw_0: require("../assets/sprites/grey_bat_nw_0.png"),
  grey_bat_nw_1: require("../assets/sprites/grey_bat_nw_1.png"),
  grey_bat_nw_2: require("../assets/sprites/grey_bat_nw_2.png"),
  grey_bat_nw_3: require("../assets/sprites/grey_bat_nw_3.png"),
  grey_bat_nw_4: require("../assets/sprites/grey_bat_nw_4.png"),  
  grey_bat_nw_5: require("../assets/sprites/grey_bat_nw_5.png"),
  grey_bat_nw_6: require("../assets/sprites/grey_bat_nw_6.png"),
  grey_bat_nw_7: require("../assets/sprites/grey_bat_nw_7.png"),
  grey_bat_nw_8: require("../assets/sprites/grey_bat_nw_8.png"),
  grey_bat_nw_9: require("../assets/sprites/grey_bat_nw_9.png"),
  grey_bat_nw_10: require("../assets/sprites/grey_bat_nw_10.png"),
  grey_bat_nw_11: require("../assets/sprites/grey_bat_nw_11.png"),
  grey_bat_nw_12: require("../assets/sprites/grey_bat_nw_12.png"),
  grey_bat_nw_13: require("../assets/sprites/grey_bat_nw_13.png"),
  grey_bat_nw_14: require("../assets/sprites/grey_bat_nw_14.png"),  
  grey_bat_nw_15: require("../assets/sprites/grey_bat_nw_15.png"),
  grey_bat_nw_16: require("../assets/sprites/grey_bat_nw_16.png"),
  grey_bat_nw_17: require("../assets/sprites/grey_bat_nw_17.png"),
  grey_bat_nw_18: require("../assets/sprites/grey_bat_nw_18.png"),
  grey_bat_nw_19: require("../assets/sprites/grey_bat_nw_19.png"), 
  
    grey_bat_sw_0: require("../assets/sprites/grey_bat_sw_0.png"),
    grey_bat_sw_1: require("../assets/sprites/grey_bat_sw_1.png"),
    grey_bat_sw_2: require("../assets/sprites/grey_bat_sw_2.png"),
    grey_bat_sw_3: require("../assets/sprites/grey_bat_sw_3.png"),
    grey_bat_sw_4: require("../assets/sprites/grey_bat_sw_4.png"),  
    grey_bat_sw_5: require("../assets/sprites/grey_bat_sw_5.png"),
    grey_bat_sw_6: require("../assets/sprites/grey_bat_sw_6.png"),
    grey_bat_sw_7: require("../assets/sprites/grey_bat_sw_7.png"),
    grey_bat_sw_8: require("../assets/sprites/grey_bat_sw_8.png"),
    grey_bat_sw_9: require("../assets/sprites/grey_bat_sw_9.png"),
    grey_bat_sw_10: require("../assets/sprites/grey_bat_sw_10.png"),
    grey_bat_sw_11: require("../assets/sprites/grey_bat_sw_11.png"),
    grey_bat_sw_12: require("../assets/sprites/grey_bat_sw_12.png"),
    grey_bat_sw_13: require("../assets/sprites/grey_bat_sw_13.png"),
    grey_bat_sw_14: require("../assets/sprites/grey_bat_sw_14.png"),  
    grey_bat_sw_15: require("../assets/sprites/grey_bat_sw_15.png"),
    grey_bat_sw_16: require("../assets/sprites/grey_bat_sw_16.png"),
    grey_bat_sw_17: require("../assets/sprites/grey_bat_sw_17.png"),
    grey_bat_sw_18: require("../assets/sprites/grey_bat_sw_18.png"),
    grey_bat_sw_19: require("../assets/sprites/grey_bat_sw_19.png"), 
  
    grey_bat_se_0: require("../assets/sprites/grey_bat_se_0.png"),
    grey_bat_se_1: require("../assets/sprites/grey_bat_se_1.png"),
    grey_bat_se_2: require("../assets/sprites/grey_bat_se_2.png"),
    grey_bat_se_3: require("../assets/sprites/grey_bat_se_3.png"),
    grey_bat_se_4: require("../assets/sprites/grey_bat_se_4.png"),  
    grey_bat_se_5: require("../assets/sprites/grey_bat_se_5.png"),
    grey_bat_se_6: require("../assets/sprites/grey_bat_se_6.png"),
    grey_bat_se_7: require("../assets/sprites/grey_bat_se_7.png"),
    grey_bat_se_8: require("../assets/sprites/grey_bat_se_8.png"),
    grey_bat_se_9: require("../assets/sprites/grey_bat_se_9.png"),
    grey_bat_se_10: require("../assets/sprites/grey_bat_se_10.png"),
    grey_bat_se_11: require("../assets/sprites/grey_bat_se_11.png"),
    grey_bat_se_12: require("../assets/sprites/grey_bat_se_12.png"),
    grey_bat_se_13: require("../assets/sprites/grey_bat_se_13.png"),
    grey_bat_se_14: require("../assets/sprites/grey_bat_se_14.png"),  
    grey_bat_se_15: require("../assets/sprites/grey_bat_se_15.png"),
    grey_bat_se_16: require("../assets/sprites/grey_bat_se_16.png"),
    grey_bat_se_17: require("../assets/sprites/grey_bat_se_17.png"),
    grey_bat_se_18: require("../assets/sprites/grey_bat_se_18.png"),
    grey_bat_se_19: require("../assets/sprites/grey_bat_se_19.png"), 
    
  grey_bat_ne_0: require("../assets/sprites/grey_bat_ne_0.png"),
  grey_bat_ne_1: require("../assets/sprites/grey_bat_ne_1.png"),
  grey_bat_ne_2: require("../assets/sprites/grey_bat_ne_2.png"),
  grey_bat_ne_3: require("../assets/sprites/grey_bat_ne_3.png"),
  grey_bat_ne_4: require("../assets/sprites/grey_bat_ne_4.png"),  
  grey_bat_ne_5: require("../assets/sprites/grey_bat_ne_5.png"),
  grey_bat_ne_6: require("../assets/sprites/grey_bat_ne_6.png"),
  grey_bat_ne_7: require("../assets/sprites/grey_bat_ne_7.png"),
  grey_bat_ne_8: require("../assets/sprites/grey_bat_ne_8.png"),
  grey_bat_ne_9: require("../assets/sprites/grey_bat_ne_9.png"),
  grey_bat_ne_10: require("../assets/sprites/grey_bat_ne_10.png"),
  grey_bat_ne_11: require("../assets/sprites/grey_bat_ne_11.png"),
  grey_bat_ne_12: require("../assets/sprites/grey_bat_ne_12.png"),
  grey_bat_ne_13: require("../assets/sprites/grey_bat_ne_13.png"),
  grey_bat_ne_14: require("../assets/sprites/grey_bat_ne_14.png"),  
  grey_bat_ne_15: require("../assets/sprites/grey_bat_ne_15.png"),
  grey_bat_ne_16: require("../assets/sprites/grey_bat_ne_16.png"),
  grey_bat_ne_17: require("../assets/sprites/grey_bat_ne_17.png"),
  grey_bat_ne_18: require("../assets/sprites/grey_bat_ne_18.png"),
  grey_bat_ne_19: require("../assets/sprites/grey_bat_ne_19.png"),     
  
  red_bat_left_0: require("../assets/sprites/red_bat_left_0.png"),
  red_bat_left_1: require("../assets/sprites/red_bat_left_1.png"),
  red_bat_left_2: require("../assets/sprites/red_bat_left_2.png"),
  red_bat_left_3: require("../assets/sprites/red_bat_left_3.png"),
  red_bat_left_4: require("../assets/sprites/red_bat_left_4.png"),  
  red_bat_left_5: require("../assets/sprites/red_bat_left_5.png"),
  red_bat_left_6: require("../assets/sprites/red_bat_left_6.png"),
  red_bat_left_7: require("../assets/sprites/red_bat_left_7.png"),
  red_bat_left_8: require("../assets/sprites/red_bat_left_8.png"),
  red_bat_left_9: require("../assets/sprites/red_bat_left_9.png"),
  red_bat_left_10: require("../assets/sprites/red_bat_left_10.png"),
  red_bat_left_11: require("../assets/sprites/red_bat_left_11.png"),
  red_bat_left_12: require("../assets/sprites/red_bat_left_12.png"),
  red_bat_left_13: require("../assets/sprites/red_bat_left_13.png"),
  red_bat_left_14: require("../assets/sprites/red_bat_left_14.png"),  
  red_bat_left_15: require("../assets/sprites/red_bat_left_15.png"),
  red_bat_left_16: require("../assets/sprites/red_bat_left_16.png"),
  red_bat_left_17: require("../assets/sprites/red_bat_left_17.png"),
  red_bat_left_18: require("../assets/sprites/red_bat_left_18.png"),
  red_bat_left_19: require("../assets/sprites/red_bat_left_19.png"),   

  red_bat_right_0: require("../assets/sprites/red_bat_right_0.png"),
  red_bat_right_1: require("../assets/sprites/red_bat_right_1.png"),
  red_bat_right_2: require("../assets/sprites/red_bat_right_2.png"),
  red_bat_right_3: require("../assets/sprites/red_bat_right_3.png"),
  red_bat_right_4: require("../assets/sprites/red_bat_right_4.png"),  
  red_bat_right_5: require("../assets/sprites/red_bat_right_5.png"),
  red_bat_right_6: require("../assets/sprites/red_bat_right_6.png"),
  red_bat_right_7: require("../assets/sprites/red_bat_right_7.png"),
  red_bat_right_8: require("../assets/sprites/red_bat_right_8.png"),
  red_bat_right_9: require("../assets/sprites/red_bat_right_9.png"),
  red_bat_right_10: require("../assets/sprites/red_bat_right_10.png"),
  red_bat_right_11: require("../assets/sprites/red_bat_right_11.png"),
  red_bat_right_12: require("../assets/sprites/red_bat_right_12.png"),
  red_bat_right_13: require("../assets/sprites/red_bat_right_13.png"),
  red_bat_right_14: require("../assets/sprites/red_bat_right_14.png"),  
  red_bat_right_15: require("../assets/sprites/red_bat_right_15.png"),
  red_bat_right_16: require("../assets/sprites/red_bat_right_16.png"),
  red_bat_right_17: require("../assets/sprites/red_bat_right_17.png"),
  red_bat_right_18: require("../assets/sprites/red_bat_right_18.png"),
  red_bat_right_19: require("../assets/sprites/red_bat_right_19.png"),     

  red_bat_up_0: require("../assets/sprites/red_bat_up_0.png"),
  red_bat_up_1: require("../assets/sprites/red_bat_up_1.png"),
  red_bat_up_2: require("../assets/sprites/red_bat_up_2.png"),
  red_bat_up_3: require("../assets/sprites/red_bat_up_3.png"),
  red_bat_up_4: require("../assets/sprites/red_bat_up_4.png"),  
  red_bat_up_5: require("../assets/sprites/red_bat_up_5.png"),
  red_bat_up_6: require("../assets/sprites/red_bat_up_6.png"),
  red_bat_up_7: require("../assets/sprites/red_bat_up_7.png"),
  red_bat_up_8: require("../assets/sprites/red_bat_up_8.png"),
  red_bat_up_9: require("../assets/sprites/red_bat_up_9.png"),
  red_bat_up_10: require("../assets/sprites/red_bat_up_10.png"),
  red_bat_up_11: require("../assets/sprites/red_bat_up_11.png"),
  red_bat_up_12: require("../assets/sprites/red_bat_up_12.png"),
  red_bat_up_13: require("../assets/sprites/red_bat_up_13.png"),
  red_bat_up_14: require("../assets/sprites/red_bat_up_14.png"),  
  red_bat_up_15: require("../assets/sprites/red_bat_up_15.png"),
  red_bat_up_16: require("../assets/sprites/red_bat_up_16.png"),
  red_bat_up_17: require("../assets/sprites/red_bat_up_17.png"),
  red_bat_up_18: require("../assets/sprites/red_bat_up_18.png"),
  red_bat_up_19: require("../assets/sprites/red_bat_up_19.png"),

  red_bat_down_0: require("../assets/sprites/red_bat_down_0.png"),
  red_bat_down_1: require("../assets/sprites/red_bat_down_1.png"),
  red_bat_down_2: require("../assets/sprites/red_bat_down_2.png"),
  red_bat_down_3: require("../assets/sprites/red_bat_down_3.png"),
  red_bat_down_4: require("../assets/sprites/red_bat_down_4.png"),  
  red_bat_down_5: require("../assets/sprites/red_bat_down_5.png"),
  red_bat_down_6: require("../assets/sprites/red_bat_down_6.png"),
  red_bat_down_7: require("../assets/sprites/red_bat_down_7.png"),
  red_bat_down_8: require("../assets/sprites/red_bat_down_8.png"),
  red_bat_down_9: require("../assets/sprites/red_bat_down_9.png"),
  red_bat_down_10: require("../assets/sprites/red_bat_down_10.png"),
  red_bat_down_11: require("../assets/sprites/red_bat_down_11.png"),
  red_bat_down_12: require("../assets/sprites/red_bat_down_12.png"),
  red_bat_down_13: require("../assets/sprites/red_bat_down_13.png"),
  red_bat_down_14: require("../assets/sprites/red_bat_down_14.png"),  
  red_bat_down_15: require("../assets/sprites/red_bat_down_15.png"),
  red_bat_down_16: require("../assets/sprites/red_bat_down_16.png"),
  red_bat_down_17: require("../assets/sprites/red_bat_down_17.png"),
  red_bat_down_18: require("../assets/sprites/red_bat_down_18.png"),
  red_bat_down_19: require("../assets/sprites/red_bat_down_19.png"),   


  red_bat_nw_0: require("../assets/sprites/red_bat_nw_0.png"),
  red_bat_nw_1: require("../assets/sprites/red_bat_nw_1.png"),
  red_bat_nw_2: require("../assets/sprites/red_bat_nw_2.png"),
  red_bat_nw_3: require("../assets/sprites/red_bat_nw_3.png"),
  red_bat_nw_4: require("../assets/sprites/red_bat_nw_4.png"),  
  red_bat_nw_5: require("../assets/sprites/red_bat_nw_5.png"),
  red_bat_nw_6: require("../assets/sprites/red_bat_nw_6.png"),
  red_bat_nw_7: require("../assets/sprites/red_bat_nw_7.png"),
  red_bat_nw_8: require("../assets/sprites/red_bat_nw_8.png"),
  red_bat_nw_9: require("../assets/sprites/red_bat_nw_9.png"),
  red_bat_nw_10: require("../assets/sprites/red_bat_nw_10.png"),
  red_bat_nw_11: require("../assets/sprites/red_bat_nw_11.png"),
  red_bat_nw_12: require("../assets/sprites/red_bat_nw_12.png"),
  red_bat_nw_13: require("../assets/sprites/red_bat_nw_13.png"),
  red_bat_nw_14: require("../assets/sprites/red_bat_nw_14.png"),  
  red_bat_nw_15: require("../assets/sprites/red_bat_nw_15.png"),
  red_bat_nw_16: require("../assets/sprites/red_bat_nw_16.png"),
  red_bat_nw_17: require("../assets/sprites/red_bat_nw_17.png"),
  red_bat_nw_18: require("../assets/sprites/red_bat_nw_18.png"),
  red_bat_nw_19: require("../assets/sprites/red_bat_nw_19.png"), 
  
    red_bat_sw_0: require("../assets/sprites/red_bat_sw_0.png"),
    red_bat_sw_1: require("../assets/sprites/red_bat_sw_1.png"),
    red_bat_sw_2: require("../assets/sprites/red_bat_sw_2.png"),
    red_bat_sw_3: require("../assets/sprites/red_bat_sw_3.png"),
    red_bat_sw_4: require("../assets/sprites/red_bat_sw_4.png"),  
    red_bat_sw_5: require("../assets/sprites/red_bat_sw_5.png"),
    red_bat_sw_6: require("../assets/sprites/red_bat_sw_6.png"),
    red_bat_sw_7: require("../assets/sprites/red_bat_sw_7.png"),
    red_bat_sw_8: require("../assets/sprites/red_bat_sw_8.png"),
    red_bat_sw_9: require("../assets/sprites/red_bat_sw_9.png"),
    red_bat_sw_10: require("../assets/sprites/red_bat_sw_10.png"),
    red_bat_sw_11: require("../assets/sprites/red_bat_sw_11.png"),
    red_bat_sw_12: require("../assets/sprites/red_bat_sw_12.png"),
    red_bat_sw_13: require("../assets/sprites/red_bat_sw_13.png"),
    red_bat_sw_14: require("../assets/sprites/red_bat_sw_14.png"),  
    red_bat_sw_15: require("../assets/sprites/red_bat_sw_15.png"),
    red_bat_sw_16: require("../assets/sprites/red_bat_sw_16.png"),
    red_bat_sw_17: require("../assets/sprites/red_bat_sw_17.png"),
    red_bat_sw_18: require("../assets/sprites/red_bat_sw_18.png"),
    red_bat_sw_19: require("../assets/sprites/red_bat_sw_19.png"), 
  
    red_bat_se_0: require("../assets/sprites/red_bat_se_0.png"),
    red_bat_se_1: require("../assets/sprites/red_bat_se_1.png"),
    red_bat_se_2: require("../assets/sprites/red_bat_se_2.png"),
    red_bat_se_3: require("../assets/sprites/red_bat_se_3.png"),
    red_bat_se_4: require("../assets/sprites/red_bat_se_4.png"),  
    red_bat_se_5: require("../assets/sprites/red_bat_se_5.png"),
    red_bat_se_6: require("../assets/sprites/red_bat_se_6.png"),
    red_bat_se_7: require("../assets/sprites/red_bat_se_7.png"),
    red_bat_se_8: require("../assets/sprites/red_bat_se_8.png"),
    red_bat_se_9: require("../assets/sprites/red_bat_se_9.png"),
    red_bat_se_10: require("../assets/sprites/red_bat_se_10.png"),
    red_bat_se_11: require("../assets/sprites/red_bat_se_11.png"),
    red_bat_se_12: require("../assets/sprites/red_bat_se_12.png"),
    red_bat_se_13: require("../assets/sprites/red_bat_se_13.png"),
    red_bat_se_14: require("../assets/sprites/red_bat_se_14.png"),  
    red_bat_se_15: require("../assets/sprites/red_bat_se_15.png"),
    red_bat_se_16: require("../assets/sprites/red_bat_se_16.png"),
    red_bat_se_17: require("../assets/sprites/red_bat_se_17.png"),
    red_bat_se_18: require("../assets/sprites/red_bat_se_18.png"),
    red_bat_se_19: require("../assets/sprites/red_bat_se_19.png"), 
    
  red_bat_ne_0: require("../assets/sprites/red_bat_ne_0.png"),
  red_bat_ne_1: require("../assets/sprites/red_bat_ne_1.png"),
  red_bat_ne_2: require("../assets/sprites/red_bat_ne_2.png"),
  red_bat_ne_3: require("../assets/sprites/red_bat_ne_3.png"),
  red_bat_ne_4: require("../assets/sprites/red_bat_ne_4.png"),  
  red_bat_ne_5: require("../assets/sprites/red_bat_ne_5.png"),
  red_bat_ne_6: require("../assets/sprites/red_bat_ne_6.png"),
  red_bat_ne_7: require("../assets/sprites/red_bat_ne_7.png"),
  red_bat_ne_8: require("../assets/sprites/red_bat_ne_8.png"),
  red_bat_ne_9: require("../assets/sprites/red_bat_ne_9.png"),
  red_bat_ne_10: require("../assets/sprites/red_bat_ne_10.png"),
  red_bat_ne_11: require("../assets/sprites/red_bat_ne_11.png"),
  red_bat_ne_12: require("../assets/sprites/red_bat_ne_12.png"),
  red_bat_ne_13: require("../assets/sprites/red_bat_ne_13.png"),
  red_bat_ne_14: require("../assets/sprites/red_bat_ne_14.png"),  
  red_bat_ne_15: require("../assets/sprites/red_bat_ne_15.png"),
  red_bat_ne_16: require("../assets/sprites/red_bat_ne_16.png"),
  red_bat_ne_17: require("../assets/sprites/red_bat_ne_17.png"),
  red_bat_ne_18: require("../assets/sprites/red_bat_ne_18.png"),
  red_bat_ne_19: require("../assets/sprites/red_bat_ne_19.png"),    

  green_bat_left_0: require("../assets/sprites/green_bat_left_0.png"),
  green_bat_left_1: require("../assets/sprites/green_bat_left_1.png"),
  green_bat_left_2: require("../assets/sprites/green_bat_left_2.png"),
  green_bat_left_3: require("../assets/sprites/green_bat_left_3.png"),
  green_bat_left_4: require("../assets/sprites/green_bat_left_4.png"),  
  green_bat_left_5: require("../assets/sprites/green_bat_left_5.png"),
  green_bat_left_6: require("../assets/sprites/green_bat_left_6.png"),
  green_bat_left_7: require("../assets/sprites/green_bat_left_7.png"),
  green_bat_left_8: require("../assets/sprites/green_bat_left_8.png"),
  green_bat_left_9: require("../assets/sprites/green_bat_left_9.png"),
  green_bat_left_10: require("../assets/sprites/green_bat_left_10.png"),
  green_bat_left_11: require("../assets/sprites/green_bat_left_11.png"),
  green_bat_left_12: require("../assets/sprites/green_bat_left_12.png"),
  green_bat_left_13: require("../assets/sprites/green_bat_left_13.png"),
  green_bat_left_14: require("../assets/sprites/green_bat_left_14.png"),  
  green_bat_left_15: require("../assets/sprites/green_bat_left_15.png"),
  green_bat_left_16: require("../assets/sprites/green_bat_left_16.png"),
  green_bat_left_17: require("../assets/sprites/green_bat_left_17.png"),
  green_bat_left_18: require("../assets/sprites/green_bat_left_18.png"),
  green_bat_left_19: require("../assets/sprites/green_bat_left_19.png"),   

  green_bat_right_0: require("../assets/sprites/green_bat_right_0.png"),
  green_bat_right_1: require("../assets/sprites/green_bat_right_1.png"),
  green_bat_right_2: require("../assets/sprites/green_bat_right_2.png"),
  green_bat_right_3: require("../assets/sprites/green_bat_right_3.png"),
  green_bat_right_4: require("../assets/sprites/green_bat_right_4.png"),  
  green_bat_right_5: require("../assets/sprites/green_bat_right_5.png"),
  green_bat_right_6: require("../assets/sprites/green_bat_right_6.png"),
  green_bat_right_7: require("../assets/sprites/green_bat_right_7.png"),
  green_bat_right_8: require("../assets/sprites/green_bat_right_8.png"),
  green_bat_right_9: require("../assets/sprites/green_bat_right_9.png"),
  green_bat_right_10: require("../assets/sprites/green_bat_right_10.png"),
  green_bat_right_11: require("../assets/sprites/green_bat_right_11.png"),
  green_bat_right_12: require("../assets/sprites/green_bat_right_12.png"),
  green_bat_right_13: require("../assets/sprites/green_bat_right_13.png"),
  green_bat_right_14: require("../assets/sprites/green_bat_right_14.png"),  
  green_bat_right_15: require("../assets/sprites/green_bat_right_15.png"),
  green_bat_right_16: require("../assets/sprites/green_bat_right_16.png"),
  green_bat_right_17: require("../assets/sprites/green_bat_right_17.png"),
  green_bat_right_18: require("../assets/sprites/green_bat_right_18.png"),
  green_bat_right_19: require("../assets/sprites/green_bat_right_19.png"),     

  green_bat_up_0: require("../assets/sprites/green_bat_up_0.png"),
  green_bat_up_1: require("../assets/sprites/green_bat_up_1.png"),
  green_bat_up_2: require("../assets/sprites/green_bat_up_2.png"),
  green_bat_up_3: require("../assets/sprites/green_bat_up_3.png"),
  green_bat_up_4: require("../assets/sprites/green_bat_up_4.png"),  
  green_bat_up_5: require("../assets/sprites/green_bat_up_5.png"),
  green_bat_up_6: require("../assets/sprites/green_bat_up_6.png"),
  green_bat_up_7: require("../assets/sprites/green_bat_up_7.png"),
  green_bat_up_8: require("../assets/sprites/green_bat_up_8.png"),
  green_bat_up_9: require("../assets/sprites/green_bat_up_9.png"),
  green_bat_up_10: require("../assets/sprites/green_bat_up_10.png"),
  green_bat_up_11: require("../assets/sprites/green_bat_up_11.png"),
  green_bat_up_12: require("../assets/sprites/green_bat_up_12.png"),
  green_bat_up_13: require("../assets/sprites/green_bat_up_13.png"),
  green_bat_up_14: require("../assets/sprites/green_bat_up_14.png"),  
  green_bat_up_15: require("../assets/sprites/green_bat_up_15.png"),
  green_bat_up_16: require("../assets/sprites/green_bat_up_16.png"),
  green_bat_up_17: require("../assets/sprites/green_bat_up_17.png"),
  green_bat_up_18: require("../assets/sprites/green_bat_up_18.png"),
  green_bat_up_19: require("../assets/sprites/green_bat_up_19.png"),

  green_bat_down_0: require("../assets/sprites/green_bat_down_0.png"),
  green_bat_down_1: require("../assets/sprites/green_bat_down_1.png"),
  green_bat_down_2: require("../assets/sprites/green_bat_down_2.png"),
  green_bat_down_3: require("../assets/sprites/green_bat_down_3.png"),
  green_bat_down_4: require("../assets/sprites/green_bat_down_4.png"),  
  green_bat_down_5: require("../assets/sprites/green_bat_down_5.png"),
  green_bat_down_6: require("../assets/sprites/green_bat_down_6.png"),
  green_bat_down_7: require("../assets/sprites/green_bat_down_7.png"),
  green_bat_down_8: require("../assets/sprites/green_bat_down_8.png"),
  green_bat_down_9: require("../assets/sprites/green_bat_down_9.png"),
  green_bat_down_10: require("../assets/sprites/green_bat_down_10.png"),
  green_bat_down_11: require("../assets/sprites/green_bat_down_11.png"),
  green_bat_down_12: require("../assets/sprites/green_bat_down_12.png"),
  green_bat_down_13: require("../assets/sprites/green_bat_down_13.png"),
  green_bat_down_14: require("../assets/sprites/green_bat_down_14.png"),  
  green_bat_down_15: require("../assets/sprites/green_bat_down_15.png"),
  green_bat_down_16: require("../assets/sprites/green_bat_down_16.png"),
  green_bat_down_17: require("../assets/sprites/green_bat_down_17.png"),
  green_bat_down_18: require("../assets/sprites/green_bat_down_18.png"),
  green_bat_down_19: require("../assets/sprites/green_bat_down_19.png"),                 
  
  green_bat_nw_0: require("../assets/sprites/green_bat_nw_0.png"),
  green_bat_nw_1: require("../assets/sprites/green_bat_nw_1.png"),
  green_bat_nw_2: require("../assets/sprites/green_bat_nw_2.png"),
  green_bat_nw_3: require("../assets/sprites/green_bat_nw_3.png"),
  green_bat_nw_4: require("../assets/sprites/green_bat_nw_4.png"),  
  green_bat_nw_5: require("../assets/sprites/green_bat_nw_5.png"),
  green_bat_nw_6: require("../assets/sprites/green_bat_nw_6.png"),
  green_bat_nw_7: require("../assets/sprites/green_bat_nw_7.png"),
  green_bat_nw_8: require("../assets/sprites/green_bat_nw_8.png"),
  green_bat_nw_9: require("../assets/sprites/green_bat_nw_9.png"),
  green_bat_nw_10: require("../assets/sprites/green_bat_nw_10.png"),
  green_bat_nw_11: require("../assets/sprites/green_bat_nw_11.png"),
  green_bat_nw_12: require("../assets/sprites/green_bat_nw_12.png"),
  green_bat_nw_13: require("../assets/sprites/green_bat_nw_13.png"),
  green_bat_nw_14: require("../assets/sprites/green_bat_nw_14.png"),  
  green_bat_nw_15: require("../assets/sprites/green_bat_nw_15.png"),
  green_bat_nw_16: require("../assets/sprites/green_bat_nw_16.png"),
  green_bat_nw_17: require("../assets/sprites/green_bat_nw_17.png"),
  green_bat_nw_18: require("../assets/sprites/green_bat_nw_18.png"),
  green_bat_nw_19: require("../assets/sprites/green_bat_nw_19.png"), 
  
    green_bat_sw_0: require("../assets/sprites/green_bat_sw_0.png"),
    green_bat_sw_1: require("../assets/sprites/green_bat_sw_1.png"),
    green_bat_sw_2: require("../assets/sprites/green_bat_sw_2.png"),
    green_bat_sw_3: require("../assets/sprites/green_bat_sw_3.png"),
    green_bat_sw_4: require("../assets/sprites/green_bat_sw_4.png"),  
    green_bat_sw_5: require("../assets/sprites/green_bat_sw_5.png"),
    green_bat_sw_6: require("../assets/sprites/green_bat_sw_6.png"),
    green_bat_sw_7: require("../assets/sprites/green_bat_sw_7.png"),
    green_bat_sw_8: require("../assets/sprites/green_bat_sw_8.png"),
    green_bat_sw_9: require("../assets/sprites/green_bat_sw_9.png"),
    green_bat_sw_10: require("../assets/sprites/green_bat_sw_10.png"),
    green_bat_sw_11: require("../assets/sprites/green_bat_sw_11.png"),
    green_bat_sw_12: require("../assets/sprites/green_bat_sw_12.png"),
    green_bat_sw_13: require("../assets/sprites/green_bat_sw_13.png"),
    green_bat_sw_14: require("../assets/sprites/green_bat_sw_14.png"),  
    green_bat_sw_15: require("../assets/sprites/green_bat_sw_15.png"),
    green_bat_sw_16: require("../assets/sprites/green_bat_sw_16.png"),
    green_bat_sw_17: require("../assets/sprites/green_bat_sw_17.png"),
    green_bat_sw_18: require("../assets/sprites/green_bat_sw_18.png"),
    green_bat_sw_19: require("../assets/sprites/green_bat_sw_19.png"), 
  
    green_bat_se_0: require("../assets/sprites/green_bat_se_0.png"),
    green_bat_se_1: require("../assets/sprites/green_bat_se_1.png"),
    green_bat_se_2: require("../assets/sprites/green_bat_se_2.png"),
    green_bat_se_3: require("../assets/sprites/green_bat_se_3.png"),
    green_bat_se_4: require("../assets/sprites/green_bat_se_4.png"),  
    green_bat_se_5: require("../assets/sprites/green_bat_se_5.png"),
    green_bat_se_6: require("../assets/sprites/green_bat_se_6.png"),
    green_bat_se_7: require("../assets/sprites/green_bat_se_7.png"),
    green_bat_se_8: require("../assets/sprites/green_bat_se_8.png"),
    green_bat_se_9: require("../assets/sprites/green_bat_se_9.png"),
    green_bat_se_10: require("../assets/sprites/green_bat_se_10.png"),
    green_bat_se_11: require("../assets/sprites/green_bat_se_11.png"),
    green_bat_se_12: require("../assets/sprites/green_bat_se_12.png"),
    green_bat_se_13: require("../assets/sprites/green_bat_se_13.png"),
    green_bat_se_14: require("../assets/sprites/green_bat_se_14.png"),  
    green_bat_se_15: require("../assets/sprites/green_bat_se_15.png"),
    green_bat_se_16: require("../assets/sprites/green_bat_se_16.png"),
    green_bat_se_17: require("../assets/sprites/green_bat_se_17.png"),
    green_bat_se_18: require("../assets/sprites/green_bat_se_18.png"),
    green_bat_se_19: require("../assets/sprites/green_bat_se_19.png"), 
    
  green_bat_ne_0: require("../assets/sprites/green_bat_ne_0.png"),
  green_bat_ne_1: require("../assets/sprites/green_bat_ne_1.png"),
  green_bat_ne_2: require("../assets/sprites/green_bat_ne_2.png"),
  green_bat_ne_3: require("../assets/sprites/green_bat_ne_3.png"),
  green_bat_ne_4: require("../assets/sprites/green_bat_ne_4.png"),  
  green_bat_ne_5: require("../assets/sprites/green_bat_ne_5.png"),
  green_bat_ne_6: require("../assets/sprites/green_bat_ne_6.png"),
  green_bat_ne_7: require("../assets/sprites/green_bat_ne_7.png"),
  green_bat_ne_8: require("../assets/sprites/green_bat_ne_8.png"),
  green_bat_ne_9: require("../assets/sprites/green_bat_ne_9.png"),
  green_bat_ne_10: require("../assets/sprites/green_bat_ne_10.png"),
  green_bat_ne_11: require("../assets/sprites/green_bat_ne_11.png"),
  green_bat_ne_12: require("../assets/sprites/green_bat_ne_12.png"),
  green_bat_ne_13: require("../assets/sprites/green_bat_ne_13.png"),
  green_bat_ne_14: require("../assets/sprites/green_bat_ne_14.png"),  
  green_bat_ne_15: require("../assets/sprites/green_bat_ne_15.png"),
  green_bat_ne_16: require("../assets/sprites/green_bat_ne_16.png"),
  green_bat_ne_17: require("../assets/sprites/green_bat_ne_17.png"),
  green_bat_ne_18: require("../assets/sprites/green_bat_ne_18.png"),
  green_bat_ne_19: require("../assets/sprites/green_bat_ne_19.png"),      
};


export default spriteGraphics;