
let spriteData =
{
virus: { left: ['virus'], right: ['virus'], up: ['virus'], down: ['virus'],
 radius: 0.9, weapon: false, pickup: false, deadly: true, hitpoints: 15, speed: 3, score: 35, generator: null, genchance: 0, circle: 0},
brown_virus: { left: ['brown_virus'], right: ['brown_virus'], up: ['brown_virus'], down: ['brown_virus'],
 radius: 0.9, weapon: false, pickup: false, deadly: true, hitpoints: 10, speed: 2, score: 25, generator: null, genchance: 0, circle: 0},
purple_virus: { left: ['purple_virus'], right: ['purple_virus'], up: ['purple_virus'], down: ['purple_virus'],
 radius: 0.9, weapon: false, pickup: false, deadly: true, hitpoints: 5, speed: 2, score: 10, generator: null, genchance: 0, circle: 0},
cyan_virus: { left: ['cyan_virus'], right: ['cyan_virus'], up: ['cyan_virus'], down: ['cyan_virus'],
 radius: 0.9, weapon: false, pickup: false, deadly: true, hitpoints: 20, speed: 3, score: 50, generator: null, genchance: 0, circle: 0},


syringe: { left: ['syringe_left'], right: ['syringe_right'], up: ['syringe_up'], down: ['syringe_down'],
 radius: 0.5, weapon: true, pickup: false, deadly: false, hitpoints: 5, speed: 4, score: 0,
  generator: null, genchance: 0, circle: 0} ,
syringe_red: { left: ['syringe_red_left'], right: ['syringe_red_right'], up: ['syringe_red_up'], down: ['syringe_red_down'],
 radius: 0.5, weapon: true, pickup: false, deadly: false, hitpoints: 10, speed: 4, score: 0,
  generator: null, genchance: 0, circle: 0} ,
syringe_blue: { left: ['syringe_blue_left'], right: ['syringe_blue_right'], up: ['syringe_blue_up'], down: ['syringe_blue_down'],
 radius: 0.5, weapon: true, pickup: false, deadly: false, hitpoints: 20, speed: 4, score: 0,
  generator: null, genchance: 0, circle: 0} ,  

explosion: { left: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
right: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
up: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
down: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
  radius: 1.0, weapon: false, pickup: false, deadly: false, hitpoints: 0, speed: 0, score: 0, generator: null, genchance: 0, circle:0 },
purple_testtube: { left:['purple_testtube'], right: ['purple_testtube'], up: ['purple_testtube'], down: ['purple_testtube'],
  radius: 0.5, weapon: false, pickup: false, deadly: true, hitpoints: 60, speed: 0, score: 200, generator: 'purple_virus', genchance: 0.01, circle:0
},
brown_testtube: { left:['brown_testtube'], right: ['brown_testtube'], up: ['brown_testtube'], down: ['brown_testtube'],
  radius: 0.5, weapon: false, pickup: false, deadly: true, hitpoints: 100, speed: 0, score: 300, generator: 'brown_virus', genchance: 0.01, circle:0
},
black_testtube: { left:['black_testtube'], right: ['black_testtube'], up: ['black_testtube'], down: ['black_testtube'],
  radius: 0.5, weapon: false, pickup: false, deadly: true, hitpoints: 150, speed: 0, score: 500, generator: 'virus', genchance: 0.01, circle:0
},
cyan_testtube: { left:['cyan_testtube'], right: ['cyan_testtube'], up: ['cyan_testtube'], down: ['cyan_testtube'],
  radius: 0.5, weapon: false, pickup: false, deadly: true, hitpoints: 200, speed: 0, score: 750, generator: 'cyan_virus', genchance: 0.01, circle:0
},
red_key: {
 left:['red_key'], right: ['red_key'], up: ['red_key'], down: ['red_key'],
  radius: 0.8, weapon: false, pickup: true, deadly: false, hitpoints: 60, speed: 0, score: 1000, generator: null, genchance: 0.00, circle:0
},
red_door: {
  left:['red_door_1','red_door_2','red_door_3','red_door_4'],
  right:['red_door_1','red_door_2','red_door_3','red_door_4'],  
  up:['red_door_1','red_door_2','red_door_3','red_door_4'],
  down:['red_door_1','red_door_2','red_door_3','red_door_4'],
  radius: 1.0, weapon: false, door: 'red_key', pickup: false, deadly: false, hitpoints: 0, speed: 0, score: 1000, generator: null, genchance: 0.00,
},
green_door: {
  left:['green_door_1','green_door_2','green_door_3','green_door_4'],
  right:['green_door_1','green_door_2','green_door_3','green_door_4'],  
  up:['green_door_1','green_door_2','green_door_3','green_door_4'],
  down:['green_door_1','green_door_2','green_door_3','green_door_4'],
  radius: 1.0, weapon: false, pickup: false, door: 'green_key', deadly: false, hitpoints: 0, speed: 0, score: 1200, generator: null, genchance: 0.00,
},
yellow_door: {
  left:['yellow_door_1','yellow_door_2','yellow_door_3','yellow_door_4'],
  right:['yellow_door_1','yellow_door_2','yellow_door_3','yellow_door_4'],  
  up:['yellow_door_1','yellow_door_2','yellow_door_3','yellow_door_4'],
  down:['yellow_door_1','yellow_door_2','yellow_door_3','yellow_door_4'],
  radius: 1.0, weapon: false, pickup: false, door: 'yellow_key',deadly: false, hitpoints: 0, speed: 0, score: 1500, generator: null, genchance: 0.00,
},
blue_door: {
  left:['blue_door_1','blue_door_2','blue_door_3','blue_door_4'],
  right:['blue_door_1','blue_door_2','blue_door_3','blue_door_4'],  
  up:['blue_door_1','blue_door_2','blue_door_3','blue_door_4'],
  down:['blue_door_1','blue_door_2','blue_door_3','blue_door_4'],
  radius: 1.0, weapon: false, pickup: false, door:'blue_key', deadly: false, hitpoints: 0, speed: 0, score: 1500, generator: null, genchance: 0.00,
},

green_key: {
  left:['green_key'], right: ['green_key'], up: ['green_key'], down: ['green_key'],
  radius: 0.8, weapon: false, pickup: true, deadly: false, hitpoints: 60, speed: 0, score: 1200, generator: null, genchance: 0.00, circle:0
},
yellow_key: {
  left:['yellow_key'], right: ['yellow_key'], up: ['yellow_key'], down: ['yellow_key'],
  radius: 0.8, weapon: false, pickup: true, deadly: false, hitpoints: 60, speed: 0, score: 1500, generator: null, genchance: 0.00, circle:0
},
blue_key: {
  left:['blue_key'], right: ['yellow_key'], up: ['yellow_key'], down: ['yellow_key'],
  radius: 0.8, weapon: false, pickup: true, deadly: false, hitpoints: 60, speed: 0, score: 1500, generator: null, genchance: 0.00, circle:0
},
crown: {
  left:['crown'], right: ['crown'], up: ['crown'], down: ['crown'],
  radius: 0.5, weapon: false, pickup: true, deadly: false, hitpoints: 60, speed: 0, score: 2000, generator: null, genchance: 0.00, circle:0
},
life1: {
  left: ['life'], right: ['life'], up: ['life'], down: ['life'],
  radius: 0.7, weopen: false, pickup: true, deadly: false, hitpoint: 60, speed: 0, score: 500, generator: null, genchance: 0.0
},
life2: {
  left: ['life'], right: ['life'], up: ['life'], down: ['life'],
  radius: 0.7, weopen: false, pickup: true, deadly: false, hitpoint: 60, speed: 0, score: 500, generator: null, genchance: 0.0
},
life3: {
  left: ['life'], right: ['life'], up: ['life'], down: ['life'],
  radius: 0.7, weopen: false, pickup: true, deadly: false, hitpoint: 60, speed: 0, score: 500, generator: null, genchance: 0.0
},
weapon_red: { left: ['syringe_red_left'], right: ['syringe_red_right'], up: ['syringe_red_up'], down: ['syringe_red_down'],
 radius: 0.5, weapon: false, pickup: true, deadly: false, hitpoints: 10, speed: 0, score: 1000,
  generator: null, genchance: 0, circle: 0} ,
weapon_blue: { left: ['syringe_blue_left'], right: ['syringe_blue_right'], up: ['syringe_blue_up'], down: ['syringe_blue_down'],
 radius: 0.5, weapon: false, pickup: true, deadly: false, hitpoints: 10, speed: 0, score: 2000,
  generator: null, genchance: 0, circle: 0} ,  

grey_bowl: {left:['grey_bowl'], right:['grey_bowl'], up:['grey_bowl'], down:['grey_bowl'],
 radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 100, speed: 0, score: 500, generator: 'grey_bat', genchance: 0.01, circle: 0},
 red_bowl: {left:['red_bowl'], right:['red_bowl'], up:['red_bowl'], down:['red_bowl'],
  radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 150, speed: 0, score: 1000, generator: 'red_bat', genchance: 0.015, circle: 0},
  green_bowl: {left:['green_bowl'], right:['green_bowl'], up:['green_bowl'], down:['green_bowl'],
   radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 200, speed: 0, score: 2000, generator: 'green_bat', genchance: 0.02, circle: 0},
   

  
player: { left: [
  'globeTrotter_left_0',
  'globeTrotter_left_1',
  'globeTrotter_left_2',
  'globeTrotter_left_3',
  'globeTrotter_left_4',
  'globeTrotter_left_5',
  'globeTrotter_left_6',
  'globeTrotter_left_7',
  'globeTrotter_left_8',
  'globeTrotter_left_9',
  'globeTrotter_left_10',
  'globeTrotter_left_11',
  'globeTrotter_left_12',
  'globeTrotter_left_13',
  'globeTrotter_left_14',
  'globeTrotter_left_15',    
],
right: [
  'globeTrotter_right_0',
  'globeTrotter_right_1',
  'globeTrotter_right_2',
  'globeTrotter_right_3',
  'globeTrotter_right_4',
  'globeTrotter_right_5',
  'globeTrotter_right_6',
  'globeTrotter_right_7',
  'globeTrotter_right_8',
  'globeTrotter_right_9',
  'globeTrotter_right_10',
  'globeTrotter_right_11',
  'globeTrotter_right_12',
  'globeTrotter_right_13',
  'globeTrotter_right_14',
  'globeTrotter_right_15',    
],
up: [
  'globeTrotter_up_0',
  'globeTrotter_up_1',
  'globeTrotter_up_2',
  'globeTrotter_up_3',
  'globeTrotter_up_4',
  'globeTrotter_up_5',
  'globeTrotter_up_6',
  'globeTrotter_up_7',
  'globeTrotter_up_8',
  'globeTrotter_up_9',
  'globeTrotter_up_10',
  'globeTrotter_up_11',
  'globeTrotter_up_12',
  'globeTrotter_up_13',
  'globeTrotter_up_14',
  'globeTrotter_up_15',    
],
down: [
  'globeTrotter_down_0',
  'globeTrotter_down_1',
  'globeTrotter_down_2',
  'globeTrotter_down_3',
  'globeTrotter_down_4',
  'globeTrotter_down_5',
  'globeTrotter_down_6',
  'globeTrotter_down_7',
  'globeTrotter_down_8',
  'globeTrotter_down_9',
  'globeTrotter_down_10',
  'globeTrotter_down_11',
  'globeTrotter_down_12',
  'globeTrotter_down_13',
  'globeTrotter_down_14',
  'globeTrotter_down_15',    
],
 radius: 0.6, weapon: false, pickup: false, deadly: false, hitpoints: 20, speed: 2, score: 0, generator: null, genchance: 0, circle: 0},
 
 grey_bat: {
   left: ['grey_bat_left_0','grey_bat_left_1','grey_bat_left_2','grey_bat_left_3','grey_bat_left_4',
   'grey_bat_left_5','grey_bat_left_6','grey_bat_left_7','grey_bat_left_8','grey_bat_left_9',
   'grey_bat_left_10','grey_bat_left_11','grey_bat_left_12','grey_bat_left_13','grey_bat_left_14',
   'grey_bat_left_15','grey_bat_left_16','grey_bat_left_17','grey_bat_left_18','grey_bat_left_19',
   ],
    right: ['grey_bat_right_0','grey_bat_right_1','grey_bat_right_2','grey_bat_right_3','grey_bat_right_4',
    'grey_bat_right_5','grey_bat_right_6','grey_bat_right_7','grey_bat_right_8','grey_bat_right_9',
    'grey_bat_right_10','grey_bat_right_11','grey_bat_right_12','grey_bat_right_13','grey_bat_right_14',
    'grey_bat_right_15','grey_bat_right_16','grey_bat_right_17','grey_bat_right_18','grey_bat_right_19',
    ],
   up: ['grey_bat_up_0','grey_bat_up_1','grey_bat_up_2','grey_bat_up_3','grey_bat_up_4',
   'grey_bat_up_5','grey_bat_up_6','grey_bat_up_7','grey_bat_up_8','grey_bat_up_9',
   'grey_bat_up_10','grey_bat_up_11','grey_bat_up_12','grey_bat_up_13','grey_bat_up_14',
   'grey_bat_up_15','grey_bat_up_16','grey_bat_up_17','grey_bat_up_18','grey_bat_up_19',
   ],   
   down: ['grey_bat_down_0','grey_bat_down_1','grey_bat_down_2','grey_bat_down_3','grey_bat_down_4',
   'grey_bat_down_5','grey_bat_down_6','grey_bat_down_7','grey_bat_down_8','grey_bat_down_9',
   'grey_bat_down_10','grey_bat_down_11','grey_bat_down_12','grey_bat_down_13','grey_bat_down_14',
   'grey_bat_down_15','grey_bat_down_16','grey_bat_down_17','grey_bat_down_18','grey_bat_down_19',
   ],
      sw: ['grey_bat_sw_0','grey_bat_sw_1','grey_bat_sw_2','grey_bat_sw_3','grey_bat_sw_4',
      'grey_bat_sw_5','grey_bat_sw_6','grey_bat_sw_7','grey_bat_sw_8','grey_bat_sw_9',
      'grey_bat_sw_10','grey_bat_sw_11','grey_bat_sw_12','grey_bat_sw_13','grey_bat_sw_14',
      'grey_bat_sw_15','grey_bat_sw_16','grey_bat_sw_17','grey_bat_sw_18','grey_bat_sw_19',
      ],   
   nw: ['grey_bat_nw_0','grey_bat_nw_1','grey_bat_nw_2','grey_bat_nw_3','grey_bat_nw_4',
   'grey_bat_nw_5','grey_bat_nw_6','grey_bat_nw_7','grey_bat_nw_8','grey_bat_nw_9',
   'grey_bat_nw_10','grey_bat_nw_11','grey_bat_nw_12','grey_bat_nw_13','grey_bat_nw_14',
   'grey_bat_nw_15','grey_bat_nw_16','grey_bat_nw_17','grey_bat_nw_18','grey_bat_nw_19',
   ],
    ne: ['grey_bat_ne_0','grey_bat_down_1','grey_bat_down_2','grey_bat_down_3','grey_bat_down_4',
    'grey_bat_down_5','grey_bat_down_6','grey_bat_down_7','grey_bat_down_8','grey_bat_down_9',
    'grey_bat_down_10','grey_bat_down_11','grey_bat_down_12','grey_bat_down_13','grey_bat_down_14',
    'grey_bat_down_15','grey_bat_down_16','grey_bat_down_17','grey_bat_down_18','grey_bat_down_19',
    ],
   se: ['grey_bat_se_0','grey_bat_se_1','grey_bat_se_2','grey_bat_se_3','grey_bat_se_4',
   'grey_bat_se_5','grey_bat_se_6','grey_bat_se_7','grey_bat_se_8','grey_bat_se_9',
   'grey_bat_se_10','grey_bat_se_11','grey_bat_se_12','grey_bat_se_13','grey_bat_se_14',
   'grey_bat_se_15','grey_bat_se_16','grey_bat_se_17','grey_bat_se_18','grey_bat_se_19',
   ],                      
   radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 8, speed: 3, score: 20, generator: null, genchance: 0, circle: 5},
 
 red_bat: {
   left: ['red_bat_left_0','red_bat_left_1','red_bat_left_2','red_bat_left_3','red_bat_left_4',
   'red_bat_left_5','red_bat_left_6','red_bat_left_7','red_bat_left_8','red_bat_left_9',
   'red_bat_left_10','red_bat_left_11','red_bat_left_12','red_bat_left_13','red_bat_left_14',
   'red_bat_left_15','red_bat_left_16','red_bat_left_17','red_bat_left_18','red_bat_left_19',
   ],
    right: ['red_bat_right_0','red_bat_right_1','red_bat_right_2','red_bat_right_3','red_bat_right_4',
    'red_bat_right_5','red_bat_right_6','red_bat_right_7','red_bat_right_8','red_bat_right_9',
    'red_bat_right_10','red_bat_right_11','red_bat_right_12','red_bat_right_13','red_bat_right_14',
    'red_bat_right_15','red_bat_right_16','red_bat_right_17','red_bat_right_18','red_bat_right_19',
    ],
   up: ['red_bat_up_0','red_bat_up_1','red_bat_up_2','red_bat_up_3','red_bat_up_4',
   'red_bat_up_5','red_bat_up_6','red_bat_up_7','red_bat_up_8','red_bat_up_9',
   'red_bat_up_10','red_bat_up_11','red_bat_up_12','red_bat_up_13','red_bat_up_14',
   'red_bat_up_15','red_bat_up_16','red_bat_up_17','red_bat_up_18','red_bat_up_19',
   ],   
   down: ['red_bat_down_0','red_bat_down_1','red_bat_down_2','red_bat_down_3','red_bat_down_4',
   'red_bat_down_5','red_bat_down_6','red_bat_down_7','red_bat_down_8','red_bat_down_9',
   'red_bat_down_10','red_bat_down_11','red_bat_down_12','red_bat_down_13','red_bat_down_14',
   'red_bat_down_15','red_bat_down_16','red_bat_down_17','red_bat_down_18','red_bat_down_19',
   ],    
      sw: ['red_bat_sw_0','red_bat_sw_1','red_bat_sw_2','red_bat_sw_3','red_bat_sw_4',
      'red_bat_sw_5','red_bat_sw_6','red_bat_sw_7','red_bat_sw_8','red_bat_sw_9',
      'red_bat_sw_10','red_bat_sw_11','red_bat_sw_12','red_bat_sw_13','red_bat_sw_14',
      'red_bat_sw_15','red_bat_sw_16','red_bat_sw_17','red_bat_sw_18','red_bat_sw_19',
      ],   
   nw: ['red_bat_nw_0','red_bat_nw_1','red_bat_nw_2','red_bat_nw_3','red_bat_nw_4',
   'red_bat_nw_5','red_bat_nw_6','red_bat_nw_7','red_bat_nw_8','red_bat_nw_9',
   'red_bat_nw_10','red_bat_nw_11','red_bat_nw_12','red_bat_nw_13','red_bat_nw_14',
   'red_bat_nw_15','red_bat_nw_16','red_bat_nw_17','red_bat_nw_18','red_bat_nw_19',
   ],
    ne: ['red_bat_ne_0','red_bat_down_1','red_bat_down_2','red_bat_down_3','red_bat_down_4',
    'red_bat_down_5','red_bat_down_6','red_bat_down_7','red_bat_down_8','red_bat_down_9',
    'red_bat_down_10','red_bat_down_11','red_bat_down_12','red_bat_down_13','red_bat_down_14',
    'red_bat_down_15','red_bat_down_16','red_bat_down_17','red_bat_down_18','red_bat_down_19',
    ],
   se: ['red_bat_se_0','red_bat_se_1','red_bat_se_2','red_bat_se_3','red_bat_se_4',
   'red_bat_se_5','red_bat_se_6','red_bat_se_7','red_bat_se_8','red_bat_se_9',
   'red_bat_se_10','red_bat_se_11','red_bat_se_12','red_bat_se_13','red_bat_se_14',
   'red_bat_se_15','red_bat_se_16','red_bat_se_17','red_bat_se_18','red_bat_se_19',
   ],  
   radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 12, speed: 4, score: 50, generator: null, genchance: 0.0, circle: 5},
 
  green_bat: {
    left: ['green_bat_left_0','green_bat_left_1','green_bat_left_2','green_bat_left_3','green_bat_left_4',
    'green_bat_left_5','green_bat_left_6','green_bat_left_7','green_bat_left_8','green_bat_left_9',
    'green_bat_left_10','green_bat_left_11','green_bat_left_12','green_bat_left_13','green_bat_left_14',
    'green_bat_left_15','green_bat_left_16','green_bat_left_17','green_bat_left_18','green_bat_left_19',
    ],
     right: ['green_bat_right_0','green_bat_right_1','green_bat_right_2','green_bat_right_3','green_bat_right_4',
     'green_bat_right_5','green_bat_right_6','green_bat_right_7','green_bat_right_8','green_bat_right_9',
     'green_bat_right_10','green_bat_right_11','green_bat_right_12','green_bat_right_13','green_bat_right_14',
     'green_bat_right_15','green_bat_right_16','green_bat_right_17','green_bat_right_18','green_bat_right_19',
     ],
    up: ['green_bat_up_0','green_bat_up_1','green_bat_up_2','green_bat_up_3','green_bat_up_4',
    'green_bat_up_5','green_bat_up_6','green_bat_up_7','green_bat_up_8','green_bat_up_9',
    'green_bat_up_10','green_bat_up_11','green_bat_up_12','green_bat_up_13','green_bat_up_14',
    'green_bat_up_15','green_bat_up_16','green_bat_up_17','green_bat_up_18','green_bat_up_19',
    ],   
    down: ['green_bat_down_0','green_bat_down_1','green_bat_down_2','green_bat_down_3','green_bat_down_4',
    'green_bat_down_5','green_bat_down_6','green_bat_down_7','green_bat_down_8','green_bat_down_9',
    'green_bat_down_10','green_bat_down_11','green_bat_down_12','green_bat_down_13','green_bat_down_14',
    'green_bat_down_15','green_bat_down_16','green_bat_down_17','green_bat_down_18','green_bat_down_19',
    ],
      sw: ['green_bat_sw_0','green_bat_sw_1','green_bat_sw_2','green_bat_sw_3','green_bat_sw_4',
      'green_bat_sw_5','green_bat_sw_6','green_bat_sw_7','green_bat_sw_8','green_bat_sw_9',
      'green_bat_sw_10','green_bat_sw_11','green_bat_sw_12','green_bat_sw_13','green_bat_sw_14',
      'green_bat_sw_15','green_bat_sw_16','green_bat_sw_17','green_bat_sw_18','green_bat_sw_19',
      ],   
   nw: ['green_bat_nw_0','green_bat_nw_1','green_bat_nw_2','green_bat_nw_3','green_bat_nw_4',
   'green_bat_nw_5','green_bat_nw_6','green_bat_nw_7','green_bat_nw_8','green_bat_nw_9',
   'green_bat_nw_10','green_bat_nw_11','green_bat_nw_12','green_bat_nw_13','green_bat_nw_14',
   'green_bat_nw_15','green_bat_nw_16','green_bat_nw_17','green_bat_nw_18','green_bat_nw_19',
   ],
    ne: ['green_bat_ne_0','green_bat_down_1','green_bat_down_2','green_bat_down_3','green_bat_down_4',
    'green_bat_down_5','green_bat_down_6','green_bat_down_7','green_bat_down_8','green_bat_down_9',
    'green_bat_down_10','green_bat_down_11','green_bat_down_12','green_bat_down_13','green_bat_down_14',
    'green_bat_down_15','green_bat_down_16','green_bat_down_17','green_bat_down_18','green_bat_down_19',
    ],
   se: ['green_bat_se_0','green_bat_se_1','green_bat_se_2','green_bat_se_3','green_bat_se_4',
   'green_bat_se_5','green_bat_se_6','green_bat_se_7','green_bat_se_8','green_bat_se_9',
   'green_bat_se_10','green_bat_se_11','green_bat_se_12','green_bat_se_13','green_bat_se_14',
   'green_bat_se_15','green_bat_se_16','green_bat_se_17','green_bat_se_18','green_bat_se_19',
   ],          
    radius: 0.6, weapon: false, pickup: false, deadly: true, hitpoints: 15, speed: 5, score: 100, generator: null, genchance: 0, circle: 5},




};

export default spriteData;